<script setup lang="ts">
// Импорт компонента заголовка
import Heading from "../components/ui/Heading.vue"
</script>

<template>
	<!-- Страница "О нас" -->
	<section class="about">
		<div class="wrapper">
			<heading text="About 🔎" />

			<!-- Блок "Дисклеймер" -->
			<p class="disclaimer">
				<span>Kick Culture</span> isn't real store. This is a pet project made
				by
				<a
					title="Go to my github profile"
					target="_blank"
					href="https://github.com/Qaddis"
					>Qaddis</a
				>.
			</p>

			<!-- Блок "Технологии" -->
			<div class="techs">
				<!-- Вступление -->
				<span>
					In it I tried to implement an example of a real store using:
				</span>

				<!-- Список использованных библиотек и фреймворков -->
				<ul>
					<li>Vite</li>
					<li>Vue</li>
					<li>Vue Router</li>
					<li>Pinia</li>
					<li>SCSS</li>
				</ul>

				<!-- Прочее (карточки товаров и личная собственность) -->
				<p>
					Products cards were generated by
					<a title="Go to leonardo.ai" href="https://leonardo.ai/"
						>Leonardo AI</a
					>, the names were invented by myself, any resemblance to real brands
					is accidental.
				</p>
			</div>

			<!-- Блок "Использованные материалы" -->
			<div class="credits">
				<!-- Источник, откуда взяты шрифты -->
				<h3>
					Fonts (taken from
					<a title="Go to fonts.google.com" href="https://fonts.google.com/"
						>Google Font</a
					>):
				</h3>

				<!-- Список использованных шрифтов -->
				<ul>
					<li>Peralta</li>
					<li>Quicksand</li>
					<li>Work Sans</li>
				</ul>

				<!-- Использованные иконки (svg) и источник -->
				<p>
					<b>Icons</b> (sneaker (background), cart, left arrow, Github logo, VK
					logo, Telegram logo) taken from
					<a title="Go to iconfinder.com" href="https://iconfinder.com/">
						Iconfinder
					</a>
					.
				</p>
			</div>
		</div>
	</section>
</template>

<style scoped lang="scss">
.about {
	width: 100%;
	height: 100%;
	padding: 50px 25px;
}

.wrapper {
	max-width: 1140px;
	margin: 0 auto;

	display: flex;
	flex-direction: column;
	align-items: center;
	row-gap: 20px;
}

.disclaimer {
	font-size: 1.2rem;

	span {
		font-family: "Peralta", serif;
		font-weight: 600;
		background: var(--gradient);
		background-clip: text;
		color: transparent;
	}

	a {
		color: #5e0ecf;
		font-family: var(--header-font);
		text-shadow: 0 0 8px #5e0ecf;
	}
}

.techs {
	display: flex;
	flex-direction: column;
	align-items: center;

	p {
		text-align: center;

		a {
			text-decoration: underline;
			font-weight: 600;
			color: #8966f8;
		}
	}

	ul {
		margin-bottom: 10px;
		list-style: disc;

		li {
			font-weight: 600;

			&::marker {
				font-weight: normal;
				color: var(--dark);
			}

			&:first-child {
				color: #bd34fe;
			}

			&:nth-child(2) {
				color: #41b883;
			}

			&:nth-child(3) {
				color: #30a46c;
			}

			&:nth-child(4) {
				color: #ffde61;
			}

			&:last-child {
				color: #cc6498;
			}
		}
	}
}

.credits {
	display: flex;
	flex-direction: column;
	align-items: center;

	a {
		color: var(--violet);
		text-decoration: underline;
	}

	h3 {
		font-weight: 600;
	}

	ul {
		list-style: disc;

		li:first-child {
			font-family: "Peralta", sans;
		}

		li:nth-child(2) {
			font-family: var(--header-font);
		}

		li:last-child {
			font-family: var(--main-font);
			font-weight: 600;
		}
	}
}
</style>
