export const cards = [
	{
		image: "/card_1.png",
		title: "yostep air 3",
		price: 79.99,
		discount: 20,
		isPopular: false,
	},
	{
		image: "/card_2.png",
		title: "yostep contrastmoon",
		price: 82.5,
		discount: 10,
		isPopular: false,
	},
	{
		image: "/card_3.png",
		title: "yostep ego",
		price: 89.95,
		discount: 0,
		isPopular: false,
	},
	{
		image: "/card_4.png",
		title: "yostep typhoon",
		price: 85.0,
		discount: 5,
		isPopular: true,
	},
	{
		image: "/card_5.png",
		title: "yostep ego 2",
		price: 92.0,
		discount: 0,
		isPopular: true,
	},
	{
		image: "/card_6.png",
		title: "yostep sunstroke",
		price: 88.0,
		discount: 0,
		isPopular: true,
	},
	{
		image: "/card_7.png",
		title: "yostep air 2",
		price: 78.5,
		discount: 0,
		isPopular: false,
	},
	{
		image: "/card_8.png",
		title: "yostep air",
		price: 75.0,
		discount: 0,
		isPopular: false,
	},
];
